export const environment = {
  production: true,
  // Default to relative /api path — nginx reverse-proxies to the backend.
  // These values can be overridden at runtime via assets/config/app-config.json
  // which is generated by the Docker entrypoint (see docker-entrypoint.sh).
  apiBaseUrl: '/api',
  authPath: '/auth',
  websocketUrl: '',  // empty = same origin, resolved at runtime
  pushPublicKey: ''
};
