import { bootstrapApplication } from '@angular/platform-browser';
import { setAssetPath } from 'ionicons';
import { RouteReuseStrategy, provideRouter, withPreloading, PreloadAllModules, withInMemoryScrolling, withViewTransitions } from '@angular/router';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';
import { provideServiceWorker } from '@angular/service-worker';
import { isDevMode, ErrorHandler, APP_INITIALIZER } from '@angular/core';
import { provideTransloco } from '@jsverse/transloco';
import { TranslocoHttpLoader } from './app/core/i18n/transloco.loader';
import { firstValueFrom } from 'rxjs';

import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';
import { provideHttpClient, withInterceptors, withInterceptorsFromDi, HTTP_INTERCEPTORS } from '@angular/common/http';
import { authInterceptor } from './app/core/interceptors/auth.interceptor';
import { HttpErrorInterceptor } from './app/core/interceptors/http-error.interceptor';
import { GlobalErrorHandler } from './app/core/handlers/global-error.handler';
import { AppConfigService } from './app/core/services/app-config.service';
import { AuthService } from './app/core/services/auth.service';
import { environment } from './environments/environment';
import { provideStore } from '@ngrx/store';
import { provideEffects } from '@ngrx/effects';
import { provideStoreDevtools } from '@ngrx/store-devtools';
import { authReducer, authFeatureKey } from './app/store/auth/auth.reducer';
import {
  loginEffect,
  registerEffect,
  logoutEffect,
  restoreSessionEffect,
} from './app/store/auth/auth.effects';

// Configure ionicons to load assets from CDN (ensures getAssetPath works in dev/prod)
setAssetPath('https://cdn.jsdelivr.net/npm/ionicons/dist/');

// In local development, aggressively disable any previously installed service
// worker so updated UI code is always loaded instead of stale cached bundles.
if (!environment.production && typeof window !== 'undefined' && 'serviceWorker' in navigator) {
  navigator.serviceWorker.getRegistrations().then((registrations) => {
    registrations.forEach((registration) => {
      registration.unregister().catch(() => {
        // Ignore unregister errors in dev; this is a best-effort cleanup.
      });
    });
  });
}

// In local development, cookies are host-bound. If one tab uses 127.0.0.1 and
// another uses localhost, auth restore may fail between tabs. Normalize to
// localhost to keep a single origin for all tabs.
if (typeof window !== 'undefined' && window.location.hostname === '127.0.0.1') {
  const { protocol, port, pathname, search, hash } = window.location;
  const target = `${protocol}//localhost${port ? `:${port}` : ''}${pathname}${search}${hash}`;
  window.location.replace(target);
}

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    { provide: ErrorHandler, useClass: GlobalErrorHandler },
    { provide: HTTP_INTERCEPTORS, useClass: HttpErrorInterceptor, multi: true },
    // Load runtime config (assets/config/app-config.json) before app boots.
    // In production Docker builds this file is generated by docker-entrypoint.sh.
    {
      provide: APP_INITIALIZER,
      useFactory: (cfg: AppConfigService) => () => cfg.load(),
      deps: [AppConfigService],
      multi: true,
    },
    // Ensure HttpClient is provided before other framework providers that may
    // instantiate services which depend on it (Ionic/router can create
    // components early). Placing provideHttpClient before provideIonicAngular
    // avoids `NG0201: No provider found for _HttpClient` in some setups.
    provideHttpClient(
      withInterceptors([authInterceptor]),
      withInterceptorsFromDi()
    ),
    // Silently restore the session from the HttpOnly refresh_token cookie.
    // This runs after HttpClient is available so the refresh call can be made.
    {
      provide: APP_INITIALIZER,
      useFactory: (auth: AuthService) => () => firstValueFrom(auth.tryRestoreSession()),
      deps: [AuthService],
      multi: true,
    },
    provideIonicAngular(),
    provideRouter(
      routes,
      withPreloading(PreloadAllModules),
      withInMemoryScrolling({ scrollPositionRestoration: 'enabled', anchorScrolling: 'enabled' }),
      withViewTransitions()
    ),
    provideTransloco({
      config: {
        availableLangs: ['en', 'pt', 'es'],
        defaultLang: 'en',
        reRenderOnLangChange: true,
        prodMode: !isDevMode(),
      },
      loader: TranslocoHttpLoader
    }),
    provideServiceWorker('ngsw-worker.js', {
      enabled: environment.production,
      registrationStrategy: 'registerWhenStable:30000'
    }),
    // ─── NgRx Store ─────────────────────────────────────────────────────────
    provideStore({ [authFeatureKey]: authReducer }),
    provideEffects({ loginEffect, registerEffect, logoutEffect, restoreSessionEffect }),
    provideStoreDevtools({
      maxAge: 25,
      logOnly: environment.production,
      connectInZone: true,
    }),
  ],
}).catch(err => {
  console.error("ERROR-> ", err);
});
